apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: huddle
type: Opaque
stringData:
  LIVEKIT_API_KEY: API5nz4FNHjEYTE
  LIVEKIT_API_SECRET: w5WCZGKoaDcm2B8x5QdMWf0XiOgJ6hNNCSoeEN6igMi
  JWT_SECRET: c2VjcmV0LWp3dC1rZXktZm9yLWh1ZGRsZS1hcHAtMjAyNXh4eHh4eA==
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
