apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: huddle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: klm89/huddle-frontend:0f43f1337f986570114803f920a7d4347c79462b
          ports:
            - containerPort: 80
