apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: huddle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: klm89/huddle-frontend:0430737acdd14ab6d5c56c2eaef509dbc6e437aa
          ports:
            - containerPort: 80
