apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: huddle-postgres
  namespace: huddle
spec:
  instances: 3

  bootstrap:
    initdb:
      database: muxvideorooms
      owner: huddle
      secret:
        name: postgres-secret
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS pgcrypto

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  storage:
    size: 1Gi
